# Generated by Django 3.1.2 on 2022-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField(verbose_name='Дата')),
                ('name', models.TextField(default='Coin', verbose_name='Название')),
                ('url_lot', models.URLField(unique=True, verbose_name='Ссылка на лот')),
                ('url_saler', models.URLField(verbose_name='Ссылка на продавца')),
                ('status', models.TextField(verbose_name='Статус')),
                ('post_price', models.TextField(max_length=50, verbose_name='Почтовый ценник')),
                ('current_price', models.PositiveIntegerField(default=0, verbose_name='Текущая цена')),
                ('my_current_price', models.PositiveIntegerField(default=0, verbose_name='Моя текущая цена')),
                ('stack', models.PositiveIntegerField(default=0, verbose_name='Ставка')),
                ('name_saler', models.TextField(verbose_name='Имя продавца')),
                ('comment_id', models.PositiveIntegerField(default=0, verbose_name='Последний коммент')),
                ('buy', models.TextField(default='No', verbose_name='Оплачено/Неоплачено')),
                ('step', models.PositiveIntegerField(default=50, verbose_name='Step')),
            ],
            options={
                'verbose_name': 'Таблица торгов в ВК',
            },
        ),
    ]
