# Generated by Django 3.1.2 on 2022-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_parser', '0002_comments2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salers1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_saler', models.TextField(verbose_name='Имя продавца')),
            ],
            options={
                'verbose_name': 'Черный список в ВК',
            },
        ),
    ]
